#!/usr/bin/env node
// Renders the Homebrew formula from a release archive, after checking the archive matches
// its .sha256 file. Usage:
//   node scripts/render-formula.mjs --archive ABS_PATH --url HTTPS_OR_FILE_URL --out ABS_PATH
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { basename, isAbsolute, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';

const fail = (message) => {
  console.error(message);
  process.exit(1);
};

const { values } = parseArgs({ options: { archive: { type: 'string' }, url: { type: 'string' }, out: { type: 'string' } } });
const { archive, url, out } = values;
if (!archive || !url || !out) fail('Usage: node scripts/render-formula.mjs --archive ABS_PATH --url HTTPS_OR_FILE_URL --out ABS_PATH');
if (!isAbsolute(archive) || !isAbsolute(out)) fail('--archive and --out must be absolute paths');
if (basename(out) !== 'gattini-watch.rb') fail('The formula file must be named gattini-watch.rb');

const { version } = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const name = `gattini-watch-${version}.tgz`;
if (basename(archive) !== name) fail(`Archive must be ${name} for package version ${version}`);

const sha256 = createHash('sha256').update(readFileSync(archive)).digest('hex');
const recorded = readFileSync(`${archive}.sha256`, 'utf8').trim().split(/\s+/)[0];
if (recorded !== sha256) fail(`Archive SHA-256 ${sha256} differs from ${archive}.sha256 (${recorded})`);

let source;
try {
  source = new URL(url);
} catch {
  fail('--url must be an absolute https: or file: URL');
}
if (source.protocol !== 'https:' && source.protocol !== 'file:') fail('--url must use https: or file:');
if (source.username || source.password || source.search || source.hash || /["'\\\n\r#]/.test(url)) fail('--url must not carry credentials, a query, a fragment or quotes');
if (decodeURIComponent(source.pathname.split('/').at(-1)) !== name) fail(`--url must end in ${name}`);
if (source.protocol === 'file:' && resolve(fileURLToPath(source)) !== resolve(archive)) fail('A file: URL must point at the verified archive');

const template = readFileSync(new URL('../packaging/homebrew/gattini-watch.rb', import.meta.url), 'utf8');
const formula = template
  .replace(/^# Template:.*\n/, '# Generated by scripts/render-formula.mjs from a checksum-verified release archive.\n')
  .replace('@URL@', url)
  .replace('@SHA256@', sha256);
writeFileSync(out, formula, { mode: 0o644 });
console.log(out);
